spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      username: ${MONGO_USER:admin}
      password: ${MONGO_PASSWORD:admin}
      port: ${MONGO_PORT:27017}
      database: barber-moustache
      authentication-database: admin
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  show-actuator: true