version: '3.4'
services:
  projetobase:
    container_name: projeto-base
    image: jianrk/barber-moustache-server:latest
    restart: always
    environment:
      MONGO_HOST: mongodb
      MONGO_USER: root
      MONGO_PASSWORD: root
    ports:
      - 9000:9000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - mongo-express

  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    restart: always
    volumes:
      - ./dbdata:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=barber-moustache
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb

